# Generated by Django 4.2.1 on 2023-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.AddField(
            model_name='data',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
