# Generated by Django 4.2.1 on 2023-05-13 18:43

import data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_data_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.CharField(default='', max_length=128, validators=[data.validators.validate_password_strength]),
        ),
        migrations.AlterField(
            model_name='data',
            name='name_user',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
