# Generated by Django 4.2.1 on 2023-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_data_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name_user',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
