# Generated by Django 4.2.1 on 2023-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_data_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
